# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3515da74fd4ee8c9b5f918fa217320c39c18654c5a0923335c7229c50dc2ce9dc59e2680b4f783db858088a3615a5ba63b41863e8a106f717e2bfc4281019ed3

test:
  secret_key_base: ddf6d9782ff12f03a2953fee02b70dc156a0b479f7e1d25936a3e9299a4ce02d8bf32e1edced68b6473f0ee850bc9471c8f4d3c241875bdc44634b94c4eb41c6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
